### ISSUE TITLE
published security advisories

### ISSUE THREAD

**Issue by erhade** [linaro-swg/optee_examples#102]
Hi,

I have recently discovered a vulnerability in this project ([https://github.com/linaro-swg/optee_examples](https://github.com/linaro-swg/optee_examples/security)) and I would like to bring it to your attention. I believe that this vulnerability could potentially cause harm to your users and compromise the security of your project. In light of this, I would like to request that you enable the "published security advisories" feature for your project on GitHub. This feature allows you to create a dedicated space on your project page for publishing security advisories and keeping your users informed about any vulnerabilities that are discovered. 

Thank you for your attention to this matter. I would be happy to provide more details about the vulnerability I discovered and assist you in any way I can to resolve it.

**Comment by jbech-linaro** [comment]
Hi @erhade ,

Yes, please go a head and report the issue here: https://github.com/OP-TEE/optee_os/security/advisories. You can use the "New draft security advisory" there. I'm aware of the being another location, but we've so far been able to track everything related to OP-TEE security issues over there, so let's give it a try with this one as well. // Thanks Joakim

**Comment by erhade** [comment]
thanks.
