### ISSUE TITLE
REE FS - TA Database

### ISSUE THREAD

**Issue by nathan-menhorn** [linaro-swg/optee_examples#31]
All,

I have some questions with regards to the Trusted Application database. I understand the basics from what is published around the web but I have a few specific details.

1. According to https://github.com/OP-TEE/optee_os/blob/master/documentation/secure_storage.md each persistent object is assigned an internal identifier, which is an integer. Is this derived from the UUID since UUIDs are 128 bits? If not how is this number created?

2. With regards to the database file dirf.db, how is this created?

3. What protections are in place to avoid the database from getting corrupted/hacked?

4. With regards to the database, as shown in slide 11 of http://connect.linaro.org.s3.amazonaws.com/sfo17/Presentations/SFO17-309%20Secure%20storage%20updates.pdf, how is the file_number created and assigned?

5. If a TA is updated, is a new UUID assigned? If so, what prevents the old TA with the old UUID from being used?

**Comment by etienne-lms** [comment]
> 1. each persistent object is assigned an internal identifier

Persistent object are identified by the UUID of the TA it belongs to and the ID  of the object (any byte size, user TA defined). Maybe see [**tee_pobj.c**/L100](https://github.com/OP-TEE/optee_os/blob/3.2.0/core/tee/tee_pobj.c#L100) and [**tee_pobj.c**/L111](https://github.com/OP-TEE/optee_os/blob/3.2.0/core/tee/tee_pobj.c#L111).

Regarding the effective storage in the secure filesystem, the object identifier depends on the storage itself. You will note that is all case, it is built from the TA UUID and the object ID defined by the user TA:
* For REE FS storage, see [`set_name()`](https://github.com/OP-TEE/optee_os/blob/3.2.0/core/tee/tee_ree_fs.c#L646) and [`tee_fs_dirfile_find()`](https://github.com/OP-TEE/optee_os/blob/3.2.0/core/tee/fs_dirfile.c#L197).
The integer identifier you refer to is a specific identifier used as file name in the Linux filesystem. It is disconnected from the object UUID/ID. It set from 
 [`tee_fs_dirfile_get_tmp()`](https://github.com/OP-TEE/optee_os/blob/3.2.0/core/tee/fs_dirfile.c#L178).
* For RPMB filesystem, see [`tee_svc_storage_create_filename()`](https://github.com/OP-TEE/optee_os/blob/3.2.0/core/tee/tee_svc_storage.c#L98).

> 2. With regards to the database file dirf.db, how is this created?

Sorry, I could not find the exact point where **dirf.db** is created the first time TEE attempts to access the "REE FS secure storage" and file is not found.


> 3. What protections are in place to avoid the database from getting corrupted/hacked?

With REE FS secure storage, the database can be modified by the REE but the content is protect by a hashtree that catches corruptions and discard content if corrupted. This requires a root node hash to be stored in a secure non-volatile memory (as an RPMB partition).

With RPMB FS secure storage, the RPMB protocol ensures TEE is gets the expected content and REE cannot write into the HW media (unless REE has the provisioned RPMBkey of course). The only thing REE could do is to modify read/write content while is traverses the REE. On TEE RPMB read requests, TEE will detect the data corruption (any likely discard the data). For TEE RPMB write requests, RPMB itself while refuse to write corrupted data.

> 4. (...) how is the file_number created and assigned?

I think the answer relates to 2. above ([`tee_fs_dirfile_get_tmp()`](https://github.com/OP-TEE/optee_os/blob/3.2.0/core/tee/fs_dirfile.c#L178)).

> 5. If a TA is updated, is a new UUID assigned? If so, what prevents the old TA with the old UUID from being used?

TA cannot change its UUID. Otherwise, it is considered as another TA.

(Please feel free to crosscheck these information)

**Comment by nathan-menhorn** [comment]
Thank you for the clarification.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
