### ISSUE TITLE
Hashing in TA [Beginner].

### ISSUE THREAD

**Issue by Gerryyq** [linaro-swg/optee_examples#53]
Hello again, 

I'm trying to hash a key, and storing that hashed key within my TA.
I understand, that `hmac_sha1()` is a function that I could use, but I'm not certain if I'm using it correctly, as I don't quite understand the usage of the parameters. Given that `key`, is the desired data to be hashed. I'm assuming that `out` would contain the hashed result, and frankly quite clueless what `in` is used for, despite the comments, much appreciated if anyone could provide any form of clarity! 

> static TEE_Result hmac_sha1(const uint8_t *key, const size_t keylen,
			    const uint8_t *in, const size_t inlen,
			    uint8_t *out, uint32_t *outlen)
>  *  @param key       The secret key
>  *  @param keylen    The length of the secret key (bytes)
>  *  @param in        The data to HMAC
>  *  @param inlen     The length of the data to HMAC (bytes)
>  *  @param out       [out] Destination of the authentication tag
>  *  @param outlen    [in/out] Max size and resulting size of authentication tag

Snippet of my code for illustration purposes, in calling `hmac_sha1()`, with reference from HOTP example.
```
char hashKey[50];
uint8_t mac[SHA1_HASH_SIZE];
uint32_t mac_len = sizeof(mac);
uint8_t counter[] = { 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0 };
res = hmac_sha1(hashKey, sizeof(hashKey), counter, sizeof(counter), mac, &mac_len);
printf("\nHASHED VALUE OF HASHKEY = %u\n", mac);
```

I get "HASHED VALUE OF HASHKEY = 10737761984".
The question is, am I doing it right?
Cheers! (:

*Edited* 
I hope I've got it right this time, just need to do a loop for `mac` and print out the values as hexadecimal.
```

res = hmac_sha1(hashKey, sizeof(hashKey), counter, sizeof(counter), mac, &mac_len);

for (i = 0; i < mac_len; i++)
{
	temp[0] = '\0';
	snprintf(temp, sizeof(temp),"%x", mac[i]);
	my_strcat(hashedKeyValue, temp);
}
printf("\nHASHED VALUE OF HASHKEY = %s\n", hashedKeyValue);
```

**Comment by jbech-linaro** [comment]
As a toy example, let's say we want to hash "abc". If I take it in pseudo language, then `hmac_sha1` in `hotp`. 
```c
uint8_t myfinalhash[20];
hmac_sha1("thisismykey", 11, "abc", 3,  myfinalhash, 20);
hexdump(myfinalhash, 20);
```
A hexdump function would produce the hash for "abc": a9993e364706816aba3e25717850c26c9cd0d89d

> I hope I've got it right this time, just need to do a loop for `mac` and print out the values as hexadecimal.

Exactly, just printf the result will not work. That's why I pseudo added the `hexdump` in the example above.

**Comment by Gerryyq** [comment]
Thank you, @jbech-linaro , for the clarification!! 👍

**Comment by Gerryyq** [comment]
Hi @jbech-linaro ,

Sorry to bother, is there another function I could call for hashing just a text, without providing a key?
For example,
```
uint8_t myfinalhash[20];
hash_sha1("Text", sizeof("Text"), myfinalhash, 20);
```

**Comment by jbech-linaro** [comment]
Yes, you can just do a SHA-1 directly, but if you want to wrap that similar to how I did with HMAC-SHA1, then you will need to change calls to the `TEE_....` functions, since you need SHA-1 parameters instead. All details for this can be found in the [GP specifications](https://optee.readthedocs.io/architecture/globalplatform_api.html) / [FAQ](https://optee.readthedocs.io/faq/faq.html#q-which-apis-have-been-implemented-in-op-tee).
